apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
namePrefix: dev-
labels:
  - pairs:
      env: dev
    includeSelectors: false
    includeTemplates: true
images:
  - name: frontend
    newName: ghcr.io/stefanprodan/podinfo
    newTag: 6.7.0
  - name: backend
    newName: ghcr.io/stefanprodan/podinfo
    newTag: 6.7.0
resources:
  - namespace.yaml
  - httproute.yaml
  - ../../base
configMapGenerator:
  - name: frontend-config
    literals:
      - PODINFO_UI_COLOR=#34577c
      - PODINFO_UI_MESSAGE=Welcome to the dev
      - PODINFO_BACKEND_URL=http://dev-backend:9898/echo
    options:
      disableNameSuffixHash: true
  - name: backend-config
    literals:
      - PODINFO_UI_COLOR=#34577c
      - PODINFO_UI_MESSAGE=Backend dev
    options:
      disableNameSuffixHash: true
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: frontend
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: backend
