apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo-dev
namePrefix: dev-
labels:
  - pairs:
      env: dev
    includeSelectors: false
    includeTemplates: true
resources:
  - namespace.yaml
  - httproute.yaml
  - ../../base
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: podinfo
