apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo-dev
namePrefix: dev-
labels:
  - pairs:
      env: dev
    includeSelectors: false
    includeTemplates: true
resources:
  - namespace.yaml
  - httproute.yaml
  - ../../base
configMapGenerator:
  - name: podinfo-config
    literals:
      - PODINFO_UI_COLOR=#34577c
      - PODINFO_UI_MESSAGE=Welcome to the dev
    options:
      disableNameSuffixHash: true
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: podinfo
