apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: backend
  namespace: qa
spec:
  hosts:
    - qa-backend-info.sand.pit.im
  ports:
    - number: 80
      name: http
      protocol: HTTP
      targetPort: 9898
  resolution: DNS
  endpoints:
    - address: backend.qa.svc.cluster.local
