apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo-qa
namePrefix: qa-
labels:
  - pairs:
      env: qa
    includeSelectors: false
    includeTemplates: true
resources:
  - namespace.yaml
  - httproute.yaml
  - ../../base
configMapGenerator:
  - name: podinfo-config
    literals:
      - PODINFO_UI_COLOR=#3EB489
      - PODINFO_UI_MESSAGE=Welcome to the qa
    options:
      disableNameSuffixHash: true
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: podinfo
