apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: backend
spec:
  chart:
    spec:
      version: 6.8.0
  values:
    replicaCount: 2
    ui:
      color: "#3EB489"
      message: "Backend qa"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frontend
spec:
  chart:
    spec:
      version: 6.8.0
  values:
    replicaCount: 2
    ui:
      color: "#3EB489"
      message: "Welcome to the qa"
    backend: http://qa-backend-info.sand.pit.im/echo
