---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: simple-app-prod
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: simple-app
  path: ./overlays/prod
  prune: true
  wait: true
  timeout: 5m
  postBuild:
    substitute:
      env_tier: "prod"
      frontend_version: "6.9.0"
      backend_version: "6.9.0"
