---
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: frontend
spec:
  provider: gatewayapi:v1
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  service:
    port: 9898
    targetPort: 9898
    gatewayRefs:
      - name: sandpit
        namespace: istio-ingress
        group: gateway.networking.k8s.io
        kind: Gateway
    hosts:
      - ${env_tier}-info.sand.pit.im
  analysis:
    interval: 10s
    threshold: 5
    maxWeight: 50
    stepWeight: 10
    webhooks:
      - name: functional-check
        type: pre-rollout
        url: http://frontend-canary.${env_tier}:9898/echo
        timeout: 5s
