---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: backend
spec:
  interval: 10m
  chart:
    spec:
      version: ${backend_version}
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: apps
              version: v1
              kind: Deployment
              name: backend
            patch: |-
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: backend
              spec:
                template:
                  metadata:
                    labels:
                      app.kubernetes.io/version: "${backend_version}"
  values:
    fullnameOverride: backend
    replicaCount: 1
    ui:
      message: "Backend ${env_tier}"
