---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: backend
spec:
  interval: 10m
  chart:
    spec:
      version: 6.8.0
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  values:
    podAnnotations:
      app.komodor.com/app: "https://github.com/uzubtsou/simple-app"
      app.komodor.com/app.ref: main
    fullnameOverride: backend
    replicaCount: 1
    ui:
      message: "Backend ${env_tier}"
