apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: simple-app
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/uzubtsou/simple-app
  ref:
    branch: main
