---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: simple-app-qa
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: simple-app
  path: ./overlays/qa
  prune: true
  wait: true
  timeout: 5m
